export const styles = {
  layout: {
    height: '100vh',
    width: '100vw',
    display: 'flex',
    padding: '20px',
    gap: '20px',
    boxSizing: 'border-box',
    overflow: 'hidden',
    position: 'fixed',
    top: 0,
    left: 0,
  },
  sidebar: {
    width: '320px',
    minWidth: '320px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    height: '100%',
  },
  sidebarHeader: {
    padding: '24px',
    borderBottom: '1px solid var(--border-light)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandTitle: {
    fontSize: '1.4rem',
    fontWeight: '700',
    letterSpacing: '-0.02em',
  },
  iconButton: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-light)',
    width: '36px',
    height: '36px',
    borderRadius: 'var(--radius-md)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatList: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px',
    minHeight: 0,
  },
  sectionTitle: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: 'var(--text-muted)',
    letterSpacing: '0.05em',
    marginBottom: '12px',
    paddingLeft: '8px',
  },
  emptyState: {
    padding: '24px',
    textAlign: 'center',
    color: 'var(--text-secondary)',
    fontSize: '0.9rem',
    background: 'var(--bg-input)',
    borderRadius: 'var(--radius-md)',
    border: '1px dashed var(--border-light)',
  },
  primaryButton: {
    background: 'var(--gradient-primary)',
    color: '#fff',
    padding: '8px 16px',
    borderRadius: 'var(--radius-sm)',
    fontSize: '0.85rem',
    fontWeight: '500',
  },
  secondaryButton: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    padding: '10px 20px',
    borderRadius: 'var(--radius-sm)',
    fontSize: '0.9rem',
    fontWeight: '500',
    border: '1px solid var(--border-light)',
  },
  ghostButton: {
    background: 'transparent',
    color: 'var(--text-secondary)',
    padding: '10px 20px',
    borderRadius: 'var(--radius-sm)',
    fontSize: '0.9rem',
    fontWeight: '500',
  },
  chatItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px',
    borderRadius: 'var(--radius-md)',
    cursor: 'pointer',
    marginBottom: '4px',
    transition: 'all 0.2s ease',
  },
  chatItemActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px',
    borderRadius: 'var(--radius-md)',
    cursor: 'pointer',
    marginBottom: '4px',
    background: 'var(--bg-input)',
    border: '1px solid var(--border-light)',
  },
  chatAvatar: {
    width: '44px',
    height: '44px',
    borderRadius: '12px',
    background: 'var(--bg-input)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1rem',
    flexShrink: 0,
  },
  chatInfo: {
    flex: 1,
    minWidth: 0,
  },
  chatName: {
    fontSize: '0.95rem',
    fontWeight: '500',
    color: 'var(--text-primary)',
    marginBottom: '2px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  chatPreview: {
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  chatTime: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
  },
  sidebarFooter: {
    padding: '20px 24px',
    borderTop: '1px solid var(--border-light)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'var(--bg-sidebar-footer)',
  },
  userProfile: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  userAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '600',
    color: '#fff',
  },
  userDetails: {
    display: 'flex',
    flexDirection: 'column',
  },
  userName: {
    fontSize: '0.95rem',
    fontWeight: '500',
    color: 'var(--text-primary)',
  },
  userStatus: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: '2px',
  },
  statusDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: 'var(--status-online)',
    boxShadow: '0 0 8px var(--status-online)',
  },
  logoutButton: {
    background: 'transparent',
    color: 'var(--text-muted)',
    padding: '8px',
  },
  mainChat: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minHeight: 0,
  },
  noChatSelected: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-secondary)',
    textAlign: 'center',
  },
  welcomeIcon: {
    fontSize: '3rem',
    marginBottom: '16px',
    opacity: 0.8,
  },
  welcomeTitle: {
    fontSize: '1.5rem',
    color: 'var(--text-primary)',
    marginBottom: '8px',
    fontWeight: '500',
  },
  welcomeText: {
    fontSize: '0.95rem',
    maxWidth: '300px',
    lineHeight: '1.5',
  },
  chatWindow: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  chatHeader: {
    padding: '24px',
    borderBottom: '1px solid var(--border-light)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  chatAvatarLarge: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    background: 'var(--gradient-primary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.2rem',
    fontWeight: '600',
    color: '#fff',
  },
  activeChatTitle: {
    fontSize: '1.1rem',
    fontWeight: '600',
    marginBottom: '4px',
  },
  activeChatStatus: {
    fontSize: '0.85rem',
    color: 'var(--text-secondary)',
  },
  messagesContainer: {
    flex: 1,
    padding: '24px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    minHeight: 0,
  },
  myMessageWrapper: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  otherMessageWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    gap: '10px',
  },
  myMessage: {
    maxWidth: '70%',
    padding: '12px 18px',
    background: 'var(--gradient-primary)',
    color: '#fff',
    borderRadius: '18px 18px 2px 18px',
    boxShadow: '0 4px 12px rgba(99, 102, 241, 0.2)',
  },
  otherMessage: {
    maxWidth: '70%',
    padding: '12px 18px',
    background: 'var(--bg-msg-other)',
    color: 'var(--text-primary)',
    borderRadius: '18px 18px 18px 2px',
    border: '1px solid var(--border-light)',
  },
  messageAvatar: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: 'var(--bg-input)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.8rem',
    fontWeight: '600',
    marginTop: 'auto',
  },
  messageSenderName: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: 'var(--accent-color)',
    marginBottom: '4px',
  },
  messageContent: {
    fontSize: '0.95rem',
    lineHeight: '1.5',
    wordBreak: 'break-word',
  },
  messageTime: {
    fontSize: '0.7rem',
    opacity: 0.6,
    textAlign: 'right',
    marginTop: '4px',
  },
  inputArea: {
    padding: '24px',
    borderTop: '1px solid var(--border-light)',
    display: 'flex',
    gap: '12px',
  },
  messageInput: {
    flex: 1,
    background: 'var(--bg-input)',
    border: '1px solid var(--border-light)',
    borderRadius: 'var(--radius-full)',
    padding: '14px 24px',
    color: 'var(--text-primary)',
    fontSize: '0.95rem',
  },
  sendButton: {
    width: '50px',
    height: '50px',
    borderRadius: '50%',
    background: 'var(--gradient-primary)',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'var(--bg-overlay)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    background: 'var(--bg-modal)',
    padding: '32px',
    borderRadius: 'var(--radius-lg)',
    width: '100%',
    maxWidth: '400px',
    border: '1px solid var(--border-light)',
    boxShadow: '0 20px 40px rgba(0,0,0,0.4)',
  },
  modalInput: {
    width: '100%',
    background: 'var(--bg-input)',
    border: '1px solid var(--border-light)',
    borderRadius: 'var(--radius-md)',
    padding: '12px 16px',
    color: 'var(--text-primary)',
    fontSize: '1rem',
    marginTop: '20px',
    marginBottom: '24px',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
  }
};
