export const styles = {
  layout: {
    height: '100vh',
    width: '100vw',
    display: 'flex',
    boxSizing: 'border-box',
    overflow: 'hidden',
    position: 'fixed',
    top: 0,
    left: 0,
    background: 'var(--bg-main)',
  },
  sidebar: {
    width: '340px',
    minWidth: '340px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    height: '100%',
    background: 'var(--bg-panel-solid)',
    borderRight: '1px solid var(--border-glass)',
    transition: 'all 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  sidebarHeader: {
    padding: '32px 24px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandTitle: {
    fontSize: '1.6rem',
    fontWeight: '800',
    letterSpacing: '-0.04em',
    background: 'var(--gradient-gold)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  iconButton: {
    background: 'var(--border-glass)',
    color: 'var(--text-primary)',
    width: '42px',
    height: '42px',
    borderRadius: 'var(--radius-md)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
    border: '1px solid var(--border-glass)',
    outline: 'none',
  },
  chatList: {
    flex: 1,
    overflowY: 'auto',
    padding: '0 16px 20px 16px',
    minHeight: 0,
  },
  sectionTitle: {
    fontSize: '0.7rem',
    fontWeight: '800',
    color: 'var(--text-muted)',
    letterSpacing: '0.12em',
    marginBottom: '16px',
    paddingLeft: '8px',
    textTransform: 'uppercase',
  },
  primaryButton: {
    background: 'var(--gradient-gold)',
    color: '#000',
    padding: '12px 24px',
    borderRadius: 'var(--radius-md)',
    fontSize: '0.9rem',
    fontWeight: '800',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 8px 20px rgba(245, 158, 11, 0.15)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  chatItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '16px',
    borderRadius: 'var(--radius-lg)',
    cursor: 'pointer',
    marginBottom: '8px',
    background: 'transparent',
    border: '1px solid transparent',
    transition: 'all 0.2s ease',
  },
  chatItemActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '16px',
    borderRadius: 'var(--radius-lg)',
    cursor: 'pointer',
    marginBottom: '8px',
    background: 'var(--border-glass)',
    border: '1px solid var(--border-gold)',
  },
  chatAvatar: {
    width: '46px',
    height: '46px',
    borderRadius: '14px',
    background: 'var(--border-glass)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    border: '1px solid var(--border-glass)',
  },
  userAvatar: {
    width: '42px',
    height: '42px',
    borderRadius: '14px',
    background: 'var(--gradient-gold)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '800',
    color: '#000',
  },
  statusDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: 'var(--accent-emerald)',
    boxShadow: '0 0 12px var(--accent-emerald)',
  },
  mainChat: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minHeight: 0,
    background: 'var(--bg-main)',
  },
  welcomeIcon: {
    width: '80px',
    height: '80px',
    marginBottom: '32px',
    opacity: 0.9,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '24px',
    background: 'var(--accent-emerald-glow)',
  },
  welcomeTitle: {
    fontSize: '2.8rem',
    color: 'var(--text-primary)',
    marginBottom: '12px',
    fontWeight: '800',
    letterSpacing: '-0.05em',
  },
  chatAvatarLarge: {
    width: '52px',
    height: '52px',
    borderRadius: '16px',
    background: 'var(--gradient-iq)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.4rem',
    fontWeight: '800',
    color: '#fff',
  },
  myMessage: {
    maxWidth: '75%',
    padding: '14px 20px',
    background: 'var(--gradient-iq)',
    color: '#fff',
    borderRadius: '20px 20px 4px 20px',
    fontSize: '1rem',
    lineHeight: '1.6',
    boxShadow: '0 8px 24px rgba(16, 185, 129, 0.1)',
  },
  sendButton: {
    width: '56px',
    height: '56px',
    borderRadius: '16px',
    background: 'var(--gradient-gold)',
    color: '#000',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    cursor: 'pointer',
    border: 'none',
    boxShadow: '0 8px 20px rgba(245, 158, 11, 0.15)',
  },
  sidebarFooter: {
    padding: '20px 24px',
    borderTop: '1px solid var(--border-glass)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
  },
  userProfile: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    minWidth: 0,
    flex: 1,
  },
  userName: {
    fontSize: '0.9rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  userStatus: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  modal: {
    background: 'var(--bg-panel-solid)',
    padding: '40px',
    borderRadius: 'var(--radius-xl)',
    width: '100%',
    maxWidth: '440px',
    border: '1px solid var(--border-glass)',
    boxShadow: 'var(--shadow-premium)',
  }
};
